<?php
return [
    'match_state' => [
        'Abnormal(suggest hiding)',
        'Not started',
        'First half',
        'Half-time',
        'Second half',
        'Overtime',
        'Overtime(deprecated)',
        'Penalty Shoot-out',
        'End',
        'Delay',
        'Interrupt',
        'Cut in half',
        'Cancel',
        'To be determined',
    ],
    'technical_statistics' => [
        'Unknown',
        'Goal',
        'Corner',
        'Yellow card',
        'Red card',
        'Offside',
        'Free kick',
        'Goal kick',
        'Penalty',
        'Substitution',
        'Start',
        'Midfield',
        'End',
        'Halftime score',
        'Card upgrade confirmed',
        'Penalty missed',
        'Own goal',
        'Injury time',
        'Shots on target',
        'Shots off target',
        'Attacks',
        'Dangerous Attack',
        'Ball possession',
        'Overtime is over',
        'Penalty kick ended',
        'VAR(Video assistant referee)',
        'Penalty(Penalty Shoot-out)',
        'Penalty missed(Penalty Shoot-out)',
    ],
    'event_reason' => [
        'Unknown',
        'Foul',
        'Professional foul',
        'Encroachment/Injury substitution',
        'Tactical Foul/Tactical substitution',
        'Reckless Offence',
        'Off the ball foul',
        'Persistent fouling',
        'Persistent Infringement',
        'Violent conduct',
        'Dangerous play',
        'Handball',
        'Serious Foul',
        'Professional foul last man',
        'Denied goal-scoring opportunity',
        'Time wasting',
        'Video sync done',
        'Rescinded Card',
        'Argument',
        'Dissent',
        'Foul and Abusive Language',
        'Excessive celebration',
        'Not Retreating',
        'Fight',
        'Extra flag to checker',
        'On bench',
        'Post match',
        'Other reason',
        'Unallowed field entering',
        'Entering field',
        'Leaving field',
        'Unsporting behaviour',
        'Not visible',
        'Flop',
        'Excessive usage of review signal',
        'Entering referee review area',
        'Spitting',
        'Viral',
    ],
    'data_update_types' => [
        'Unknown',
        'single match lineup',
        'bracket',
        'season standing',
        'season team statistics',
        'season player statistics',
        'season top scorer',
        'fifa men',
        'fifa women',
        'world clubs ranking',
    ],
    'incident_reason' => [
        'Other',
        'Goal awarded',
        'Goal not awarded',
        'Penalty awarded',
        'Penalty not awarded',
        'Red card given',
        'Card upgrade',
        'Mistaken identity',
    ],
    'incident_result' => [
        'Unknown',
        'Goal confirmed',
        'Goal cancelled',
        'Penalty confirmed',
        'Penalty cancelled',
        'Red card confirmed',
        'Red card cancelled',
        'Card upgrade confirmed',
        'Card upgrade cancelled',
        'Original decision',
        'Original decision changed',
    ],
    'incident_position' => [
        'neutral',
        'home team',
        'away team',
    ],
    'weather' => [
        'Unknown',
        'Cloudy',
        'Partially cloudy/rain',
        'Snow',
        'Sunny',
        'Overcast Rain/partial thunderstorm',
        'overcast',
        'mist',
        'cloudy with rain',
        'cloudy with rain',
        'cloudy with rain/partial Thunderstorms',
        'Clouds/rains and thunderstorms locally',
        'Fog',
    ],
    'companies' => [
        '2' =>	'BET365',
        '3' =>	'Crown',
        '4' =>	'10BET',
        '5' =>	'Ladbrokes',
        '6' =>	'Mansion88',
        '7' =>	'Macauslot',
        '8' =>	'SNAI',
        '9' =>	'William Hill',
        '10' =>	'Easybets',
        '11' =>	'Vcbet',
        '12' =>	'EuroBet',
        '13' =>	'Interwetten',
        '14' =>	'12bet',
        '15' =>	'Sbobet',
        '16' =>	'Wewbet',
        '17' =>	'18Bet',
        '18' =>	'Fun88',
        '21' =>	'188bet',
        '22' =>	'Pinnacle',
    ],
];
